server:
  port: 9011
  tomcat:
    accesslog:
      enabled: true

spring:
  profiles:
    active: native
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/server-configs

debug: true