server:
  port: 7080

spring:
  application:
    name: gateway
  profiles:
    active: native
  cloud:
    config:
      uri: http://localhost:9011
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
      - name: GlobalFilter
        args:
          baseMessage: Spring Cloud Gateway GlobalFilter
          preLogger: true
          postLogger: true
      routes:
      - id: book
        uri: lb://book
        predicates:
        - Path=/book/**
        filters:
        - name: BookFilter
          args:
            baseMessage: Spring Cloud Gateway BookFilter
            preLogger: true
            postLogger: true
      - id: users
        uri: lb://users
        predicates:
        - Path=/users/**
        filters:
        - name: UsersFilter
          args:
            baseMessage: Spring Cloud Gateway UsersFilter
            preLogger: true
            postLogger: true

eureka:
  instance:
    instance-id: instgateway
  client:
    service-url:
      defaultZone: http://localhost:6080/eureka/

